### ISSUE TITLE
Thiết kế màn hình chat

### ISSUE THREAD

**Issue by nghiac1d** [nghiac1d/ProjectFrondend#10]

**Comment by haphamufc** [comment]
![737C7201-9518-46BD-B0FF-56BEFE848AA2](https://user-images.githubusercontent.com/65293225/123119226-87373c80-d46d-11eb-818b-06cf17ad87ff.png)
-
![41111A85-CACF-4224-B29D-7BA3F36B0188](https://user-images.githubusercontent.com/65293225/123119244-8b635a00-d46d-11eb-8073-aff47665d605.png)

**Comment by nghiac1d** [comment]
ok r
