### ISSUE TITLE
Lên DS các chức năng cần thiết

### ISSUE THREAD

**Issue by nghiac1d** [nghiac1d/ProjectFrondend#11]

**Comment by thaiduong2208** [comment]
![197596044_338613137810900_6322929010510384669_n](https://user-images.githubusercontent.com/67571981/123121299-42140a00-d46f-11eb-87bb-3b6254ce8d1a.png)
![196003286_1232428360543213_7668034385623067922_n](https://user-images.githubusercontent.com/67571981/123121318-45a79100-d46f-11eb-8a62-7118d6347ea6.png)

**Comment by nghiac1d** [comment]
Các chức năng tiên quyết:
- Chat 1vs1.
- Chat nhóm.
- Xem lịch sử chat.
