### ISSUE TITLE
Thiết kế màn hình đăng nhập, đăng ký

### ISSUE THREAD

**Issue by nghiac1d** [nghiac1d/ProjectFrondend#8]

**Comment by thaiduong2208** [comment]
![197596044_338613137810900_6322929010510384669_n](https://user-images.githubusercontent.com/67571981/123121735-9c14cf80-d46f-11eb-817e-ab25f4f3afc2.png)
![196003286_1232428360543213_7668034385623067922_n](https://user-images.githubusercontent.com/67571981/123121747-9e772980-d46f-11eb-805e-3fcc2b1c8744.png)

**Comment by nghiac1d** [comment]
ok r
